name: Sync with notepad2

on:
  schedule:
    - cron:  '35 4 * * 1'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/sync.yml'

jobs:
  sync-scintilla:
    runs-on: ubuntu-latest      
    steps:    
        - name: Check out code into the Go module directory
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GH_TOKEN }}
              
        - name: update
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}        
          run: |
            git clone https://github.com/zufuliu/notepad4.git
            cp -r notepad4/scintilla/* ./
            rm -rf notepad4
            git remote -v
            git config user.name "auto-sync-scintilla[bot]"
            git config user.email "auto-sync-scintilla[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            git add .
            git status
            git commit -m "auto update scintilla at $(date)" .
            git push origin master
      
